[".local/share/colorscripts"]
  type = "archive"
  url = "https://gitlab.com/dwt1/shell-color-scripts/-/archive/master/shell-color-scripts-master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/fish/aliases/kubectl_aliases.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases.fish"
  refreshPeriod = "168h"
[".local/share/fonts/fira-code"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.tar.xz"
  refreshPeriod = "168h"
[".tfenv/"]
  type = "archive"
  exact = true
  url = "https://github.com/tfutils/tfenv/archive/master.tar.gz"
  refreshPeriod = "168h"
  stripComponents = 1
[".config/fish/completions/kubectx.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubectx.fish"
  refreshPeriod = "168h"
[".config/fish/completions/kubens.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubens.fish"
  refreshPeriod = "168h"
["Downloads/aws"]
  type = "archive"
  url = "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  stripComponents = 1
["Downloads/terraform-docs"]
  type = "archive"
  url = "https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz"
  stripComponents = 0
[".bin/cliphist"]
  type = "file"
  executable = true
  url = "https://github.com/sentriz/cliphist/releases/download/v0.5.0/v0.5.0-linux-amd64"

