font_family FiraCode

copy_on_select yes

# Scroll speed
wheel_scroll_multiplier 15.0
touch_scroll_multiplier 10.0

# Keymappings
map super+c    copy_to_clipboard
map super+v    paste_from_clipboard
map f1         launch --allow-remote-control kitty +kitten broadcast

include nord-kitty-theme.conf
