# GIT
abbr g 'git'
abbr ga 'git add'
abbr gaa 'git add -A'
abbr gb 'git branch'
abbr gbd 'git branch -d'
abbr gbdd 'git branch -D'
abbr gbl 'git blame'
abbr gch 'git checkout'
abbr gchb 'git checkout -b'
abbr gc 'git commit'
abbr gcm 'git commit -m'
abbr gcl 'git clone'
abbr gca 'git commit --amend -m'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr gdc 'git diff --cached'
abbr gf 'git fetch'
abbr gl 'git log'
abbr glp 'git log --patch'
abbr gls 'git log --stat'
abbr glo 'git log --pretty=oneline'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpf 'git push --force-with-lease'
abbr gpl 'git pull'
abbr gr 'git restore'
abbr grs 'git restore --staged'
abbr grm 'git remote'
abbr grb 'git rebase'
abbr gs 'git status --short'
abbr gss 'git status'
abbr gst 'git stash'

# Exa
abbr ll 'exa --long --all --group --git'
abbr lt 'exa --long --all --group --header --tree --level'
